[tool.poetry]
name = "browserpilot"
version = "0.2.42"
description = "Natural language browser automation"
authors = ["Andrew Han <handrew11@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
openai = "^0.27.1"
selenium = "^4.8.2"
tqdm = "^4.64.1"
beautifulsoup4 = "^4.11.2"
pyyaml = "^6.0"
llama-index = "^0.5.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
